CREATE TABLE IF NOT EXISTS applications (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS link_type (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS link (
    id INTEGER PRIMARY KEY NOT NULL,
    app_id INTEGER NOT NULL,
    link_type INTEGER NOT NULL,
    url VARCHAR(100) NOT NULL,
    FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (link_type) REFERENCES link_type(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS owner (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ownership (
    id INTEGER PRIMARY KEY NOT NULL,
    app_id INTEGER NOT NULL,
    owner_id INTEGER NOT NULL,
    FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (owner_id) REFERENCES owner(id) ON DELETE CASCADE ON UPDATE CASCADE
);
