CREATE TABLE IF NOT EXISTS owner (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ownership (
    id INTEGER PRIMARY KEY NOT NULL,
    app_id INTEGER NOT NULL,
    owner_id INTEGER NOT NULL,
    FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (owner_id) REFERENCES owner(id) ON DELETE CASCADE ON UPDATE CASCADE
);
